version: '3.8'

services:
  kgtt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kgtt-taxi-tours
    restart: unless-stopped
    ports:
      - "3070:3070"
    environment:
      - NODE_ENV=production
